// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMutYB816rh0jtLm-7p-K79bUpIR_irjA',
    appId: '1:187682652489:android:f2d794cd4367b48cac1a98',
    messagingSenderId: '187682652489',
    projectId: 't-store-3d785',
    storageBucket: 't-store-3d785.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_rbWNzAGj1WQxxcToL4dgWWoQuZ1po8',
    appId: '1:187682652489:ios:9e406f347193b25aac1a98',
    messagingSenderId: '187682652489',
    projectId: 't-store-3d785',
    storageBucket: 't-store-3d785.appspot.com',
    androidClientId: '187682652489-fdkq7i6engb6v3dncprqq1fck5586rvp.apps.googleusercontent.com',
    iosClientId: '187682652489-agroeq1q2nfoe3p5t066dq27qm21dqoq.apps.googleusercontent.com',
    iosBundleId: 'com.users.tStore',
  );
}
